2023-04-13 17:12:22,893 INFO root Token successfully initted: 6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c
2023-04-13 17:12:22,894 INFO root Bot successfully initted
2023-04-13 17:12:22,894 INFO root DB connected successfully, cursor created
2023-04-13 17:12:22,899 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:12:23,146 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getMe HTTP/1.1" 200 191
2023-04-13 17:12:23,155 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:12:27,676 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 398
2023-04-13 17:12:27,682 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:12:27,998 DEBUG urllib3.connectionpool https://api.telegram.org:443 "POST /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/sendMessage?chat_id=1515397583&text=%D0%9F%D0%BE%D0%B6%D0%B0%D0%BB%D1%83%D0%B9%D1%81%D1%82%D0%B0%2C+%D0%B2%D0%B2%D0%B5%D0%B4%D0%B8%D1%82%D0%B5+%D0%92%D0%B0%D1%88+%D0%B0%D0%BD%D0%B5%D0%BA%D0%B4%D0%BE%D1%82.+%D0%95%D1%81%D0%BB%D0%B8+%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D1%83%D0%BC%D0%B0%D0%BB%D0%B8+-+%2Fcancel+%D0%B2+%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C HTTP/1.1" 200 625
2023-04-13 17:12:35,064 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040603&timeout=20 HTTP/1.1" 200 397
2023-04-13 17:12:35,069 ERROR TeleBot Infinity polling exception: name 'markup' is not defined
2023-04-13 17:12:35,075 ERROR TeleBot Exception traceback:
Traceback (most recent call last):
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\favanek\main.py", line 92, in save_suggestion
    markup.add(cancel_button)
NameError: name 'markup' is not defined

2023-04-13 17:12:38,087 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:12:38,356 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040604&timeout=20 HTTP/1.1" 409 143
2023-04-13 17:12:58,362 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040604&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:13:18,453 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040604&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:13:38,548 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040604&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:13:58,639 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040604&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:14:18,723 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040604&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:14:38,818 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040604&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:14:58,980 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040604&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:15:05,008 ERROR TeleBot Infinity polling: polling exited
2023-04-13 17:15:05,008 ERROR TeleBot Break infinity polling
2023-04-13 17:15:05,009 INFO root Bot STOPPED
